{
 "title": "Corona",
 "time": { "from": "now-20d", "to": "now" },
 "panels": [
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "content": "# Corona Dashboard\n## Basic Information\nAll data is gathered from Johns Hopkins University github-respository [1] and inserted into a mariaDB with the script you can find also on github [2].\\\n[1] https://github.com/CSSEGISandData/COVID-19 \\\n[2] https://github.com/targetingsnake/Covid-19-Data-for-Grafana\n## Updating schedule and no-data problem\nUpdating-script is running at 2:00 am. For this reason, there is the possibility that that no data is shown between 5:15 am and 6:00 am in GMT+1.\\\n## Further Information\nIf you got any questions, want further information about the update script or how to import data into grafana, just mail at corona@konfuzzyus.eu."
  },
  {
   "title": "Current Infected Counter for Germany",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_originalData\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'Germany'\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Current increase to previous day for germany",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage1d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Germany'\nORDER BY date"
    }
   ]
  },
  {
   "title": "COVID-19 - Central Europe, US and Hubei (China)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Infected" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_originalData\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'Germany'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_originalData\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'Austria'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_originalData\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'Italy'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_originalData\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'France'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_originalData\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'Spain'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_originalData\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'US'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_originalData\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'China, Hubei'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_originalData\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'Sweden'\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "COVID-19 - Central Europe, US and Hubei (China)  - Percentage 1 Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "increase in %" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage1d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Germany'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage1d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Austria'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage1d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Italy'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage1d\nWHERE\n  $__timeFilter(date) AND\n  country = 'France'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage1d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Spain'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage1d\nWHERE\n  $__timeFilter(date) AND\n  country = 'US'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage1d\nWHERE\n  $__timeFilter(date) AND\n  country = 'China, Hubei'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage1d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Sweden'\nORDER BY date"
    }
   ]
  },
  {
   "title": "COVID-19 - Central Europe, US and Hubei (China)  - Difference 1 Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "increase in total persons" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_diff1d\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'Germany'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_diff1d\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'Austria'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_diff1d\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'Italy'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_diff1d\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'France'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_diff1d\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'Spain'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_diff1d\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'US'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_diff1d\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'China, Hubei'\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_diff1d\nWHERE\n  $__timeFilter(datetime) AND\n  country = 'Sweden'\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "COVID-19 - Central Europe, US and Hubei (China) - Percentage 3 Days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "increase in %" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage3d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Germany'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage3d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Austria'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage3d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Italy'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage3d\nWHERE\n  $__timeFilter(date) AND\n  country = 'France'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage3d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Spain'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage3d\nWHERE\n  $__timeFilter(date) AND\n  country = 'US'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage3d\nWHERE\n  $__timeFilter(date) AND\n  country = 'China, Hubei'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage3d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Sweden'\nORDER BY date"
    }
   ]
  },
  {
   "title": "COVID-19 - Central Europe, US and Hubei (China) - Percentage 5 Days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "increase in %" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage5d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Germany'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage5d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Austria'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage5d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Italy'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage5d\nWHERE\n  $__timeFilter(date) AND\n  country = 'France'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage5d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Spain'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage5d\nWHERE\n  $__timeFilter(date) AND\n  country = 'US'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage5d\nWHERE\n  $__timeFilter(date) AND\n  country = 'China, Hubei'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage5d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Sweden'\nORDER BY date"
    }
   ]
  },
  {
   "title": "COVID-19 - Central Europe, US and Hubei (China) - Percentage 7 Days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "increase in %" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage7d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Germany'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage7d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Austria'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage7d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Italy'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage7d\nWHERE\n  $__timeFilter(date) AND\n  country = 'France'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage7d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Spain'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage7d\nWHERE\n  $__timeFilter(date) AND\n  country = 'US'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage7d\nWHERE\n  $__timeFilter(date) AND\n  country = 'China, Hubei'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage7d\nWHERE\n  $__timeFilter(date) AND\n  country = 'Sweden'\nORDER BY date"
    }
   ]
  },
  {
   "title": "COVID-19 Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "Infected" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  country AS metric,\n  cases\nFROM 2020_originalData\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "COVID-19 Percentage 1 Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "increase in %" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage1d\nWHERE\n  $__timeFilter(date)\nORDER BY date"
    }
   ]
  },
  {
   "title": "COVID-19 - Percentage 3 Days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short", "label": "increase in %" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage3d\nWHERE\n  $__timeFilter(date)\nORDER BY date"
    }
   ]
  },
  {
   "title": "COVID-19 Percentage 5 days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "increase in %" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage5d\nWHERE\n  $__timeFilter(date)\nORDER BY date"
    }
   ]
  },
  {
   "title": "COVID-19 Percentage 7 days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short", "label": "increase in %" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  percentage\nFROM 2020_percentage7d\nWHERE\n  $__timeFilter(date)\nORDER BY date"
    }
   ]
  }
 ]
}